<?php

declare(strict_types=1);

namespace Shredio\EodhdClient\Mapper;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\EodhdClient\Payload\AnalystRatings;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Result\Failure;
use Shredio\TypeSchema\Result\WithNotices;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<AnalystRatings>
 */
final readonly class AnalystRatingsMapper extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): Failure|WithNotices|AnalystRatings
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape([
			'Rating' => $ts->nullable($ts->float()),
			'TargetPrice' => $ts->nullable($ts->float()),
			'StrongBuy' => $ts->nullable($ts->int()),
			'Buy' => $ts->nullable($ts->int()),
			'Hold' => $ts->nullable($ts->int()),
			'Sell' => $ts->nullable($ts->int()),
			'StrongSell' => $ts->nullable($ts->int()),
		]);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($values instanceof Failure) {
			return $this->withOwnDefinition($values, $context);
		}

		$notices = null;
		if ($values instanceof WithNotices) {
			$notices = $values->notices;
			$values = $values->value;
		}

		// 3. Reindex values
		$reindexedValues = [];
		$reindexedValues['rating'] = $values['Rating'];
		$reindexedValues['targetPrice'] = $values['TargetPrice'];
		$reindexedValues['strongBuy'] = $values['StrongBuy'];
		$reindexedValues['buy'] = $values['Buy'];
		$reindexedValues['hold'] = $values['Hold'];
		$reindexedValues['sell'] = $values['Sell'];
		$reindexedValues['strongSell'] = $values['StrongSell'];

		unset($values['Rating'], $values['TargetPrice'], $values['StrongBuy'], $values['Buy'], $values['Hold'], $values['Sell'], $values['StrongSell']);
		$values = $reindexedValues + $values;

		// 4. Create a new instance
		$obj = new AnalystRatings(...$values);

		return $notices === null ? $obj : new WithNotices($obj, $notices);
	}


	protected function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(AnalystRatings::class);
	}
}
