<?php

declare(strict_types=1);

namespace Shredio\EodhdClient\Mapper;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\EodhdClient\Payload\BalanceSheetStatement;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Result\Failure;
use Shredio\TypeSchema\Result\WithNotices;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<BalanceSheetStatement>
 */
final readonly class BalanceSheetStatementMapper extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): Failure|WithNotices|BalanceSheetStatement
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape(
			[
			'date' => $ts->nonEmptyString(),
			'filing_date' => $ts->nullable($ts->nonEmptyString()),
			'currency_symbol' => $ts->nullable($ts->nonEmptyString()),
			'totalAssets' => $ts->nullable($ts->float()),
			'intangibleAssets' => $ts->nullable($ts->float()),
			'earningAssets' => $ts->nullable($ts->float()),
			'otherCurrentAssets' => $ts->nullable($ts->float()),
			'totalLiab' => $ts->nullable($ts->float()),
			'totalStockholderEquity' => $ts->nullable($ts->float()),
			'deferredLongTermLiab' => $ts->nullable($ts->float()),
			'otherCurrentLiab' => $ts->nullable($ts->float()),
			'commonStock' => $ts->nullable($ts->float()),
			'capitalStock' => $ts->nullable($ts->float()),
			'retainedEarnings' => $ts->nullable($ts->float()),
			'otherLiab' => $ts->nullable($ts->float()),
			'goodWill' => $ts->nullable($ts->float()),
			'otherAssets' => $ts->nullable($ts->float()),
			'cash' => $ts->nullable($ts->float()),
			'cashAndEquivalents' => $ts->nullable($ts->float()),
			'totalCurrentLiabilities' => $ts->nullable($ts->float()),
			'currentDeferredRevenue' => $ts->nullable($ts->float()),
			'netDebt' => $ts->nullable($ts->float()),
			'shortTermDebt' => $ts->nullable($ts->float()),
			'shortLongTermDebt' => $ts->nullable($ts->float()),
			'shortLongTermDebtTotal' => $ts->nullable($ts->float()),
			'otherStockholderEquity' => $ts->nullable($ts->float()),
			'propertyPlantEquipment' => $ts->nullable($ts->float()),
			'totalCurrentAssets' => $ts->nullable($ts->float()),
			'longTermInvestments' => $ts->nullable($ts->float()),
			'netTangibleAssets' => $ts->nullable($ts->float()),
			'shortTermInvestments' => $ts->nullable($ts->float()),
			'netReceivables' => $ts->nullable($ts->float()),
			'longTermDebt' => $ts->nullable($ts->float()),
			'inventory' => $ts->nullable($ts->float()),
			'accountsPayable' => $ts->nullable($ts->float()),
			'totalPermanentEquity' => $ts->nullable($ts->float()),
			'noncontrollingInterestInConsolidatedEntity' => $ts->nullable($ts->float()),
			'temporaryEquityRedeemableNoncontrollingInterests' => $ts->nullable($ts->float()),
			'accumulatedOtherComprehensiveIncome' => $ts->nullable($ts->float()),
			'additionalPaidInCapital' => $ts->nullable($ts->float()),
			'commonStockTotalEquity' => $ts->nullable($ts->float()),
			'preferredStockTotalEquity' => $ts->nullable($ts->float()),
			'retainedEarningsTotalEquity' => $ts->nullable($ts->float()),
			'treasuryStock' => $ts->nullable($ts->float()),
			'accumulatedAmortization' => $ts->nullable($ts->float()),
			'nonCurrrentAssetsOther' => $ts->nullable($ts->float()),
			'deferredLongTermAssetCharges' => $ts->nullable($ts->float()),
			'nonCurrentAssetsTotal' => $ts->nullable($ts->float()),
			'capitalLeaseObligations' => $ts->nullable($ts->float()),
			'longTermDebtTotal' => $ts->nullable($ts->float()),
			'nonCurrentLiabilitiesOther' => $ts->nullable($ts->float()),
			'nonCurrentLiabilitiesTotal' => $ts->nullable($ts->float()),
			'negativeGoodwill' => $ts->nullable($ts->float()),
			'warrants' => $ts->nullable($ts->float()),
			'preferredStockRedeemable' => $ts->nullable($ts->float()),
			'capitalSurpluse' => $ts->nullable($ts->float()),
			'liabilitiesAndStockholdersEquity' => $ts->nullable($ts->float()),
			'cashAndShortTermInvestments' => $ts->nullable($ts->float()),
			'propertyPlantAndEquipmentGross' => $ts->nullable($ts->float()),
			'propertyPlantAndEquipmentNet' => $ts->nullable($ts->float()),
			'accumulatedDepreciation' => $ts->nullable($ts->float()),
			'netWorkingCapital' => $ts->nullable($ts->float()),
			'netInvestedCapital' => $ts->nullable($ts->float()),
			'commonStockSharesOutstanding' => $ts->nullable($ts->float()),
		],
			identifier: 'date',
		);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($values instanceof Failure) {
			return $this->withOwnDefinition($values, $context);
		}

		$notices = null;
		if ($values instanceof WithNotices) {
			$notices = $values->notices;
			$values = $values->value;
		}

		// 3. Reindex values
		$reindexedValues = [];
		$reindexedValues['filingDate'] = $values['filing_date'];
		$reindexedValues['currencySymbol'] = $values['currency_symbol'];
		$reindexedValues['nonCurrentAssetsOther'] = $values['nonCurrrentAssetsOther'];
		$reindexedValues['capitalSurplus'] = $values['capitalSurpluse'];

		unset($values['filing_date'], $values['currency_symbol'], $values['nonCurrrentAssetsOther'], $values['capitalSurpluse']);
		$values = $reindexedValues + $values;

		// 4. Create a new instance
		$obj = new BalanceSheetStatement(...$values);

		return $notices === null ? $obj : new WithNotices($obj, $notices);
	}


	protected function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(BalanceSheetStatement::class);
	}
}
