<?php

declare(strict_types=1);

namespace Shredio\EodhdClient\Mapper;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\EodhdClient\Payload\BulkEndOfDayPrice;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Result\Failure;
use Shredio\TypeSchema\Result\WithNotices;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<BulkEndOfDayPrice>
 */
final readonly class BulkEndOfDayPriceMapper extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): Failure|WithNotices|BulkEndOfDayPrice
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape(
			[
			'code' => $ts->nonEmptyString(),
			'exchange_short_name' => $ts->nonEmptyString(),
			'date' => $ts->nonEmptyString(),
			'open' => $ts->float(),
			'high' => $ts->float(),
			'low' => $ts->float(),
			'close' => $ts->float(),
			'adjusted_close' => $ts->float(),
			'volume' => $ts->union([$ts->int(), $ts->float()]),
		],
			identifier: 'code',
		);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($values instanceof Failure) {
			return $this->withOwnDefinition($values, $context);
		}

		$notices = null;
		if ($values instanceof WithNotices) {
			$notices = $values->notices;
			$values = $values->value;
		}

		// 3. Reindex values
		$reindexedValues = [];
		$reindexedValues['exchangeShortName'] = $values['exchange_short_name'];
		$reindexedValues['adjustedClose'] = $values['adjusted_close'];

		unset($values['exchange_short_name'], $values['adjusted_close']);
		$values = $reindexedValues + $values;

		// 4. Create a new instance
		$obj = new BulkEndOfDayPrice(...$values);

		return $notices === null ? $obj : new WithNotices($obj, $notices);
	}


	protected function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(BulkEndOfDayPrice::class);
	}
}
