<?php

declare(strict_types=1);

namespace Shredio\EodhdClient\Mapper;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\EodhdClient\Payload\CashFlowStatement;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Result\Failure;
use Shredio\TypeSchema\Result\WithNotices;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<CashFlowStatement>
 */
final readonly class CashFlowStatementMapper extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): Failure|WithNotices|CashFlowStatement
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape(
			[
			'date' => $ts->nonEmptyString(),
			'filing_date' => $ts->nullable($ts->nonEmptyString()),
			'currency_symbol' => $ts->nullable($ts->nonEmptyString()),
			'investments' => $ts->nullable($ts->float()),
			'changeToLiabilities' => $ts->nullable($ts->float()),
			'totalCashflowsFromInvestingActivities' => $ts->nullable($ts->float()),
			'netBorrowings' => $ts->nullable($ts->float()),
			'totalCashFromFinancingActivities' => $ts->nullable($ts->float()),
			'changeToOperatingActivities' => $ts->nullable($ts->float()),
			'netIncome' => $ts->nullable($ts->float()),
			'changeInCash' => $ts->nullable($ts->float()),
			'beginPeriodCashFlow' => $ts->nullable($ts->float()),
			'endPeriodCashFlow' => $ts->nullable($ts->float()),
			'totalCashFromOperatingActivities' => $ts->nullable($ts->float()),
			'issuanceOfCapitalStock' => $ts->nullable($ts->float()),
			'depreciation' => $ts->nullable($ts->float()),
			'otherCashflowsFromInvestingActivities' => $ts->nullable($ts->float()),
			'dividendsPaid' => $ts->nullable($ts->float()),
			'changeToInventory' => $ts->nullable($ts->float()),
			'changeToAccountReceivables' => $ts->nullable($ts->float()),
			'salePurchaseOfStock' => $ts->nullable($ts->float()),
			'otherCashflowsFromFinancingActivities' => $ts->nullable($ts->float()),
			'changeToNetincome' => $ts->nullable($ts->float()),
			'capitalExpenditures' => $ts->nullable($ts->float()),
			'changeReceivables' => $ts->nullable($ts->float()),
			'cashFlowsOtherOperating' => $ts->nullable($ts->float()),
			'exchangeRateChanges' => $ts->nullable($ts->float()),
			'cashAndCashEquivalentsChanges' => $ts->nullable($ts->float()),
			'changeInWorkingCapital' => $ts->nullable($ts->float()),
			'stockBasedCompensation' => $ts->nullable($ts->float()),
			'otherNonCashItems' => $ts->nullable($ts->float()),
			'freeCashFlow' => $ts->nullable($ts->float()),
		],
			identifier: 'date',
		);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($values instanceof Failure) {
			return $this->withOwnDefinition($values, $context);
		}

		$notices = null;
		if ($values instanceof WithNotices) {
			$notices = $values->notices;
			$values = $values->value;
		}

		// 3. Reindex values
		$reindexedValues = [];
		$reindexedValues['filingDate'] = $values['filing_date'];
		$reindexedValues['currencySymbol'] = $values['currency_symbol'];
		$reindexedValues['changeToNetIncome'] = $values['changeToNetincome'];

		unset($values['filing_date'], $values['currency_symbol'], $values['changeToNetincome']);
		$values = $reindexedValues + $values;

		// 4. Create a new instance
		$obj = new CashFlowStatement(...$values);

		return $notices === null ? $obj : new WithNotices($obj, $notices);
	}


	protected function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(CashFlowStatement::class);
	}
}
