<?php

declare(strict_types=1);

namespace Shredio\EodhdClient\Mapper;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\EodhdClient\Payload\CompanyListing;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Result\Failure;
use Shredio\TypeSchema\Result\WithNotices;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<CompanyListing>
 */
final readonly class CompanyListingMapper extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): Failure|WithNotices|CompanyListing
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape(
			[
			'Code' => $ts->nonEmptyString(),
			'Exchange' => $ts->nonEmptyString(),
			'Name' => $ts->string(),
		],
			identifier: 'Code',
		);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($values instanceof Failure) {
			return $this->withOwnDefinition($values, $context);
		}

		$notices = null;
		if ($values instanceof WithNotices) {
			$notices = $values->notices;
			$values = $values->value;
		}

		// 3. Reindex values
		$reindexedValues = [];
		$reindexedValues['code'] = $values['Code'];
		$reindexedValues['exchange'] = $values['Exchange'];
		$reindexedValues['name'] = $values['Name'];

		unset($values['Code'], $values['Exchange'], $values['Name']);
		$values = $reindexedValues + $values;

		// 4. Create a new instance
		$obj = new CompanyListing(...$values);

		return $notices === null ? $obj : new WithNotices($obj, $notices);
	}


	protected function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(CompanyListing::class);
	}
}
