<?php

declare(strict_types=1);

namespace Shredio\EodhdClient\Mapper;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\EodhdClient\Payload\CompanyOfficer;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Result\Failure;
use Shredio\TypeSchema\Result\WithNotices;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<CompanyOfficer>
 */
final readonly class CompanyOfficerMapper extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): Failure|WithNotices|CompanyOfficer
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape(
			[
			'Name' => $ts->string(),
			'Title' => $ts->nullable($ts->nonEmptyString()),
			'YearBorn' => $ts->nullable($ts->int(), ['NA']),
		],
			identifier: 'Name',
		);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($values instanceof Failure) {
			return $this->withOwnDefinition($values, $context);
		}

		$notices = null;
		if ($values instanceof WithNotices) {
			$notices = $values->notices;
			$values = $values->value;
		}

		// 3. Reindex values
		$reindexedValues = [];
		$reindexedValues['name'] = $values['Name'];
		$reindexedValues['title'] = $values['Title'];
		$reindexedValues['yearBorn'] = $values['YearBorn'];

		unset($values['Name'], $values['Title'], $values['YearBorn']);
		$values = $reindexedValues + $values;

		// 4. Create a new instance
		$obj = new CompanyOfficer(...$values);

		return $notices === null ? $obj : new WithNotices($obj, $notices);
	}


	protected function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(CompanyOfficer::class);
	}
}
