<?php

declare(strict_types=1);

namespace Shredio\EodhdClient\Mapper;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\EodhdClient\Payload\CompanyGeneral;
use Shredio\EodhdClient\TypeSchema\KeyedList;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Result\Failure;
use Shredio\TypeSchema\Result\WithNotices;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<CompanyGeneral>
 */
final readonly class CompanyGeneralMapper extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): Failure|WithNotices|CompanyGeneral
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape(
			[
			'Code' => $ts->nonEmptyString(),
			'Type' => $ts->nullable($ts->nonEmptyString()),
			'Name' => $ts->nonEmptyString(),
			'Exchange' => $ts->nonEmptyString(),
			'CurrencyCode' => $ts->nullable($ts->nonEmptyString()),
			'CurrencyName' => $ts->nullable($ts->nonEmptyString()),
			'CurrencySymbol' => $ts->nullable($ts->nonEmptyString()),
			'CountryName' => $ts->nullable($ts->nonEmptyString()),
			'CountryISO' => $ts->nullable($ts->nonEmptyString()),
			'OpenFigi' => $ts->nullable($ts->nonEmptyString()),
			'ISIN' => $ts->nullable($ts->nonEmptyString()),
			'LEI' => $ts->nullable($ts->nonEmptyString()),
			'PrimaryTicker' => $ts->nullable($ts->nonEmptyString()),
			'CIK' => $ts->nullable($ts->nonEmptyString()),
			'EmployerIdNumber' => $ts->nullable($ts->nonEmptyString()),
			'FiscalYearEnd' => $ts->nullable($ts->nonEmptyString()),
			'IPODate' => $ts->nullable($ts->nonEmptyString()),
			'InternationalDomestic' => $ts->nullable($ts->nonEmptyString()),
			'Sector' => $ts->nullable($ts->nonEmptyString()),
			'Industry' => $ts->nullable($ts->nonEmptyString()),
			'GicSector' => $ts->nullable($ts->nonEmptyString()),
			'GicGroup' => $ts->nullable($ts->nonEmptyString()),
			'GicIndustry' => $ts->nullable($ts->nonEmptyString()),
			'GicSubIndustry' => $ts->nullable($ts->nonEmptyString()),
			'Description' => $ts->nullable($ts->nonEmptyString()),
			'Address' => $ts->nullable($ts->nonEmptyString()),
			'AddressData' => $ts->nullable(new CompanyAddressMapper()),
			'Listings' => $ts->before(KeyedList::values(...), $ts->list(new CompanyListingMapper())),
			'Officers' => $ts->before(KeyedList::values(...), $ts->list(new CompanyOfficerMapper())),
			'Phone' => $ts->nullable($ts->nonEmptyString()),
			'WebURL' => $ts->nullable($ts->nonEmptyString()),
			'LogoURL' => $ts->nullable($ts->nonEmptyString()),
			'FullTimeEmployees' => $ts->nullable($ts->int()),
			'UpdatedAt' => $ts->nullable($ts->nonEmptyString()),
			'CUSIP' => $ts->optional($ts->nullable($ts->nonEmptyString())),
			'HomeCategory' => $ts->optional($ts->nullable($ts->nonEmptyString())),
			'IsDelisted' => $ts->optional($ts->nullable($ts->bool())),
		],
			identifier: 'Code',
		);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($values instanceof Failure) {
			return $this->withOwnDefinition($values, $context);
		}

		$notices = null;
		if ($values instanceof WithNotices) {
			$notices = $values->notices;
			$values = $values->value;
		}

		// 3. Reindex values
		$reindexedValues = [];
		$reindexedValues['code'] = $values['Code'];
		$reindexedValues['type'] = $values['Type'];
		$reindexedValues['name'] = $values['Name'];
		$reindexedValues['exchange'] = $values['Exchange'];
		$reindexedValues['currencyCode'] = $values['CurrencyCode'];
		$reindexedValues['currencyName'] = $values['CurrencyName'];
		$reindexedValues['currencySymbol'] = $values['CurrencySymbol'];
		$reindexedValues['countryName'] = $values['CountryName'];
		$reindexedValues['countryIso'] = $values['CountryISO'];
		$reindexedValues['openFigi'] = $values['OpenFigi'];
		$reindexedValues['isin'] = $values['ISIN'];
		$reindexedValues['lei'] = $values['LEI'];
		$reindexedValues['primaryTicker'] = $values['PrimaryTicker'];
		$reindexedValues['cik'] = $values['CIK'];
		$reindexedValues['employerIdNumber'] = $values['EmployerIdNumber'];
		$reindexedValues['fiscalYearEnd'] = $values['FiscalYearEnd'];
		$reindexedValues['ipoDate'] = $values['IPODate'];
		$reindexedValues['internationalDomestic'] = $values['InternationalDomestic'];
		$reindexedValues['sector'] = $values['Sector'];
		$reindexedValues['industry'] = $values['Industry'];
		$reindexedValues['gicSector'] = $values['GicSector'];
		$reindexedValues['gicGroup'] = $values['GicGroup'];
		$reindexedValues['gicIndustry'] = $values['GicIndustry'];
		$reindexedValues['gicSubIndustry'] = $values['GicSubIndustry'];
		$reindexedValues['description'] = $values['Description'];
		$reindexedValues['address'] = $values['Address'];
		$reindexedValues['addressData'] = $values['AddressData'];
		$reindexedValues['listings'] = $values['Listings'];
		$reindexedValues['officers'] = $values['Officers'];
		$reindexedValues['phone'] = $values['Phone'];
		$reindexedValues['webUrl'] = $values['WebURL'];
		$reindexedValues['logoUrl'] = $values['LogoURL'];
		$reindexedValues['fullTimeEmployees'] = $values['FullTimeEmployees'];
		$reindexedValues['updatedAt'] = $values['UpdatedAt'];

		if (array_key_exists('CUSIP', $values)) {
			$reindexedValues['cusip'] = $values['CUSIP'];
		}

		if (array_key_exists('HomeCategory', $values)) {
			$reindexedValues['homeCategory'] = $values['HomeCategory'];
		}

		if (array_key_exists('IsDelisted', $values)) {
			$reindexedValues['isDelisted'] = $values['IsDelisted'];
		}

		unset($values['Code'], $values['Type'], $values['Name'], $values['Exchange'], $values['CurrencyCode'], $values['CurrencyName'], $values['CurrencySymbol'], $values['CountryName'], $values['CountryISO'], $values['OpenFigi'], $values['ISIN'], $values['LEI'], $values['PrimaryTicker'], $values['CIK'], $values['EmployerIdNumber'], $values['FiscalYearEnd'], $values['IPODate'], $values['InternationalDomestic'], $values['Sector'], $values['Industry'], $values['GicSector'], $values['GicGroup'], $values['GicIndustry'], $values['GicSubIndustry'], $values['Description'], $values['Address'], $values['AddressData'], $values['Listings'], $values['Officers'], $values['Phone'], $values['WebURL'], $values['LogoURL'], $values['FullTimeEmployees'], $values['UpdatedAt'], $values['CUSIP'], $values['HomeCategory'], $values['IsDelisted']);
		$values = $reindexedValues + $values;

		// 4. Create a new instance
		$obj = new CompanyGeneral(...$values);

		return $notices === null ? $obj : new WithNotices($obj, $notices);
	}


	protected function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(CompanyGeneral::class);
	}
}
