<?php

declare(strict_types=1);

namespace Shredio\EodhdClient\Mapper;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\EodhdClient\Payload\CompanyAddress;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Result\Failure;
use Shredio\TypeSchema\Result\WithNotices;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<CompanyAddress>
 */
final readonly class CompanyAddressMapper extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): Failure|WithNotices|CompanyAddress
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape([
			'Country' => $ts->nullable($ts->nonEmptyString()),
			'Street' => $ts->optional($ts->nullable($ts->nonEmptyString())),
			'City' => $ts->optional($ts->nullable($ts->nonEmptyString())),
			'State' => $ts->optional($ts->nullable($ts->nonEmptyString())),
			'ZIP' => $ts->optional($ts->nullable($ts->nonEmptyString())),
		]);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($values instanceof Failure) {
			return $this->withOwnDefinition($values, $context);
		}

		$notices = null;
		if ($values instanceof WithNotices) {
			$notices = $values->notices;
			$values = $values->value;
		}

		// 3. Reindex values
		$reindexedValues = [];
		$reindexedValues['country'] = $values['Country'];

		if (array_key_exists('Street', $values)) {
			$reindexedValues['street'] = $values['Street'];
		}

		if (array_key_exists('City', $values)) {
			$reindexedValues['city'] = $values['City'];
		}

		if (array_key_exists('State', $values)) {
			$reindexedValues['state'] = $values['State'];
		}

		if (array_key_exists('ZIP', $values)) {
			$reindexedValues['zip'] = $values['ZIP'];
		}

		unset($values['Country'], $values['Street'], $values['City'], $values['State'], $values['ZIP']);
		$values = $reindexedValues + $values;

		// 4. Create a new instance
		$obj = new CompanyAddress(...$values);

		return $notices === null ? $obj : new WithNotices($obj, $notices);
	}


	protected function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(CompanyAddress::class);
	}
}
