<?php

declare(strict_types=1);

namespace Shredio\EodhdClient\Mapper;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\EodhdClient\Payload\Dividend;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Result\Failure;
use Shredio\TypeSchema\Result\WithNotices;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<Dividend>
 */
final readonly class DividendMapper extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): Failure|WithNotices|Dividend
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape(
			[
			'date' => $ts->nonEmptyString(),
			'declarationDate' => $ts->nullable($ts->nonEmptyString()),
			'recordDate' => $ts->nullable($ts->nonEmptyString()),
			'paymentDate' => $ts->nullable($ts->nonEmptyString()),
			'period' => $ts->nullable($ts->nonEmptyString()),
			'value' => $ts->float(),
			'unadjustedValue' => $ts->float(),
			'currency' => $ts->nullable($ts->nonEmptyString()),
		],
			identifier: 'date',
		);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($values instanceof Failure) {
			return $this->withOwnDefinition($values, $context);
		}

		$notices = null;
		if ($values instanceof WithNotices) {
			$notices = $values->notices;
			$values = $values->value;
		}

		// 3. Create a new instance
		$obj = new Dividend(...$values);

		return $notices === null ? $obj : new WithNotices($obj, $notices);
	}


	protected function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(Dividend::class);
	}
}
