<?php

declare(strict_types=1);

namespace Shredio\EodhdClient\Mapper;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\EodhdClient\Payload\EarningsTrend;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Result\Failure;
use Shredio\TypeSchema\Result\WithNotices;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<EarningsTrend>
 */
final readonly class EarningsTrendMapper extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): Failure|WithNotices|EarningsTrend
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape(
			[
			'date' => $ts->nonEmptyString(),
			'period' => $ts->nonEmptyString(),
			'growth' => $ts->nullable($ts->float()),
			'earningsEstimateAvg' => $ts->nullable($ts->float()),
			'earningsEstimateLow' => $ts->nullable($ts->float()),
			'earningsEstimateHigh' => $ts->nullable($ts->float()),
			'earningsEstimateYearAgoEps' => $ts->nullable($ts->float()),
			'earningsEstimateNumberOfAnalysts' => $ts->nullable($ts->float()),
			'earningsEstimateGrowth' => $ts->nullable($ts->float()),
			'revenueEstimateAvg' => $ts->nullable($ts->float()),
			'revenueEstimateLow' => $ts->nullable($ts->float()),
			'revenueEstimateHigh' => $ts->nullable($ts->float()),
			'revenueEstimateYearAgoEps' => $ts->nullable($ts->float()),
			'revenueEstimateNumberOfAnalysts' => $ts->nullable($ts->float()),
			'revenueEstimateGrowth' => $ts->nullable($ts->float()),
			'epsTrendCurrent' => $ts->nullable($ts->float()),
			'epsTrend7daysAgo' => $ts->nullable($ts->float()),
			'epsTrend30daysAgo' => $ts->nullable($ts->float()),
			'epsTrend60daysAgo' => $ts->nullable($ts->float()),
			'epsTrend90daysAgo' => $ts->nullable($ts->float()),
			'epsRevisionsUpLast7days' => $ts->nullable($ts->float()),
			'epsRevisionsUpLast30days' => $ts->nullable($ts->float()),
			'epsRevisionsDownLast30days' => $ts->nullable($ts->float()),
			'epsRevisionsDownLast7days' => $ts->optional($ts->nullable($ts->float())),
			'code' => $ts->optional($ts->nullable($ts->nonEmptyString())),
		],
			identifier: 'date',
		);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($values instanceof Failure) {
			return $this->withOwnDefinition($values, $context);
		}

		$notices = null;
		if ($values instanceof WithNotices) {
			$notices = $values->notices;
			$values = $values->value;
		}

		// 3. Create a new instance
		$obj = new EarningsTrend(...$values);

		return $notices === null ? $obj : new WithNotices($obj, $notices);
	}


	protected function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(EarningsTrend::class);
	}
}
