<?php

declare(strict_types=1);

namespace Shredio\EodhdClient\Mapper;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\EodhdClient\Payload\EarningsCalendarItem;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Result\Failure;
use Shredio\TypeSchema\Result\WithNotices;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<EarningsCalendarItem>
 */
final readonly class EarningsCalendarItemMapper extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): Failure|WithNotices|EarningsCalendarItem
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape(
			[
			'code' => $ts->nonEmptyString(),
			'report_date' => $ts->nonEmptyString(),
			'date' => $ts->nonEmptyString(),
			'before_after_market' => $ts->nullable($ts->nonEmptyString()),
			'currency' => $ts->nullable($ts->nonEmptyString()),
			'actual' => $ts->nullable($ts->float()),
			'estimate' => $ts->nullable($ts->float()),
			'difference' => $ts->nullable($ts->float()),
			'percent' => $ts->nullable($ts->float()),
		],
			identifier: 'code',
		);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($values instanceof Failure) {
			return $this->withOwnDefinition($values, $context);
		}

		$notices = null;
		if ($values instanceof WithNotices) {
			$notices = $values->notices;
			$values = $values->value;
		}

		// 3. Reindex values
		$reindexedValues = [];
		$reindexedValues['reportDate'] = $values['report_date'];
		$reindexedValues['beforeAfterMarket'] = $values['before_after_market'];

		unset($values['report_date'], $values['before_after_market']);
		$values = $reindexedValues + $values;

		// 4. Create a new instance
		$obj = new EarningsCalendarItem(...$values);

		return $notices === null ? $obj : new WithNotices($obj, $notices);
	}


	protected function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(EarningsCalendarItem::class);
	}
}
