<?php

declare(strict_types=1);

namespace Shredio\EodhdClient\Mapper;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\EodhdClient\Payload\EndOfDayPrice;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Result\Failure;
use Shredio\TypeSchema\Result\WithNotices;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<EndOfDayPrice>
 */
final readonly class EndOfDayPriceMapper extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): Failure|WithNotices|EndOfDayPrice
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape(
			[
			'date' => $ts->nonEmptyString(),
			'open' => $ts->float(),
			'high' => $ts->float(),
			'low' => $ts->float(),
			'close' => $ts->float(),
			'adjusted_close' => $ts->float(),
			'volume' => $ts->union([$ts->int(), $ts->float()]),
		],
			identifier: 'date',
		);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($values instanceof Failure) {
			return $this->withOwnDefinition($values, $context);
		}

		$notices = null;
		if ($values instanceof WithNotices) {
			$notices = $values->notices;
			$values = $values->value;
		}

		// 3. Reindex values
		$reindexedValues = [];
		$reindexedValues['adjustedClose'] = $values['adjusted_close'];

		unset($values['adjusted_close']);
		$values = $reindexedValues + $values;

		// 4. Create a new instance
		$obj = new EndOfDayPrice(...$values);

		return $notices === null ? $obj : new WithNotices($obj, $notices);
	}


	protected function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(EndOfDayPrice::class);
	}
}
