<?php

declare(strict_types=1);

namespace Shredio\EodhdClient\Mapper;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\EodhdClient\Payload\EsgScores;
use Shredio\EodhdClient\TypeSchema\KeyedList;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Result\Failure;
use Shredio\TypeSchema\Result\WithNotices;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<EsgScores>
 */
final readonly class EsgScoresMapper extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): Failure|WithNotices|EsgScores
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape([
			'Disclaimer' => $ts->nullable($ts->nonEmptyString()),
			'RatingDate' => $ts->nullable($ts->nonEmptyString()),
			'TotalEsg' => $ts->nullable($ts->float()),
			'TotalEsgPercentile' => $ts->nullable($ts->float()),
			'EnvironmentScore' => $ts->nullable($ts->float()),
			'EnvironmentScorePercentile' => $ts->nullable($ts->float()),
			'SocialScore' => $ts->nullable($ts->float()),
			'SocialScorePercentile' => $ts->nullable($ts->float()),
			'GovernanceScore' => $ts->nullable($ts->float()),
			'GovernanceScorePercentile' => $ts->nullable($ts->float()),
			'ControversyLevel' => $ts->nullable($ts->int()),
			'ActivitiesInvolvement' => $ts->before(KeyedList::values(...), $ts->list(new EsgActivityInvolvementMapper())),
		]);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($values instanceof Failure) {
			return $this->withOwnDefinition($values, $context);
		}

		$notices = null;
		if ($values instanceof WithNotices) {
			$notices = $values->notices;
			$values = $values->value;
		}

		// 3. Reindex values
		$reindexedValues = [];
		$reindexedValues['disclaimer'] = $values['Disclaimer'];
		$reindexedValues['ratingDate'] = $values['RatingDate'];
		$reindexedValues['totalEsg'] = $values['TotalEsg'];
		$reindexedValues['totalEsgPercentile'] = $values['TotalEsgPercentile'];
		$reindexedValues['environmentScore'] = $values['EnvironmentScore'];
		$reindexedValues['environmentScorePercentile'] = $values['EnvironmentScorePercentile'];
		$reindexedValues['socialScore'] = $values['SocialScore'];
		$reindexedValues['socialScorePercentile'] = $values['SocialScorePercentile'];
		$reindexedValues['governanceScore'] = $values['GovernanceScore'];
		$reindexedValues['governanceScorePercentile'] = $values['GovernanceScorePercentile'];
		$reindexedValues['controversyLevel'] = $values['ControversyLevel'];
		$reindexedValues['activitiesInvolvement'] = $values['ActivitiesInvolvement'];

		unset($values['Disclaimer'], $values['RatingDate'], $values['TotalEsg'], $values['TotalEsgPercentile'], $values['EnvironmentScore'], $values['EnvironmentScorePercentile'], $values['SocialScore'], $values['SocialScorePercentile'], $values['GovernanceScore'], $values['GovernanceScorePercentile'], $values['ControversyLevel'], $values['ActivitiesInvolvement']);
		$values = $reindexedValues + $values;

		// 4. Create a new instance
		$obj = new EsgScores(...$values);

		return $notices === null ? $obj : new WithNotices($obj, $notices);
	}


	protected function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(EsgScores::class);
	}
}
