<?php

declare(strict_types=1);

namespace Shredio\EodhdClient\Mapper;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\EodhdClient\Payload\Exchange;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Result\Failure;
use Shredio\TypeSchema\Result\WithNotices;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<Exchange>
 */
final readonly class ExchangeMapper extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): Failure|WithNotices|Exchange
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape(
			[
			'Name' => $ts->nonEmptyString(),
			'Code' => $ts->nonEmptyString(),
			'OperatingMIC' => $ts->nullable($ts->nonEmptyString()),
			'Country' => $ts->nullable($ts->nonEmptyString()),
			'Currency' => $ts->nullable($ts->nonEmptyString()),
			'CountryISO2' => $ts->nullable($ts->nonEmptyString()),
			'CountryISO3' => $ts->nullable($ts->nonEmptyString()),
		],
			identifier: 'Code',
		);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($values instanceof Failure) {
			return $this->withOwnDefinition($values, $context);
		}

		$notices = null;
		if ($values instanceof WithNotices) {
			$notices = $values->notices;
			$values = $values->value;
		}

		// 3. Reindex values
		$reindexedValues = [];
		$reindexedValues['name'] = $values['Name'];
		$reindexedValues['code'] = $values['Code'];
		$reindexedValues['operatingMic'] = $values['OperatingMIC'];
		$reindexedValues['country'] = $values['Country'];
		$reindexedValues['currency'] = $values['Currency'];
		$reindexedValues['countryIso2'] = $values['CountryISO2'];
		$reindexedValues['countryIso3'] = $values['CountryISO3'];

		unset($values['Name'], $values['Code'], $values['OperatingMIC'], $values['Country'], $values['Currency'], $values['CountryISO2'], $values['CountryISO3']);
		$values = $reindexedValues + $values;

		// 4. Create a new instance
		$obj = new Exchange(...$values);

		return $notices === null ? $obj : new WithNotices($obj, $notices);
	}


	protected function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(Exchange::class);
	}
}
