<?php

declare(strict_types=1);

namespace Shredio\EodhdClient\Mapper;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\EodhdClient\Payload\Highlights;
use Shredio\EodhdClient\TypeSchema\IntegerAmount;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Result\Failure;
use Shredio\TypeSchema\Result\WithNotices;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<Highlights>
 */
final readonly class HighlightsMapper extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): Failure|WithNotices|Highlights
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape([
			'MarketCapitalization' => $ts->before(IntegerAmount::roundToInt(...), $ts->nullable($ts->int())),
			'MarketCapitalizationMln' => $ts->nullable($ts->float()),
			'EBITDA' => $ts->before(IntegerAmount::roundToInt(...), $ts->nullable($ts->int())),
			'PERatio' => $ts->nullable($ts->float()),
			'PEGRatio' => $ts->nullable($ts->float()),
			'WallStreetTargetPrice' => $ts->nullable($ts->float()),
			'BookValue' => $ts->nullable($ts->float()),
			'DividendShare' => $ts->nullable($ts->float()),
			'DividendYield' => $ts->nullable($ts->float()),
			'EarningsShare' => $ts->nullable($ts->float()),
			'EPSEstimateCurrentYear' => $ts->nullable($ts->float()),
			'EPSEstimateNextYear' => $ts->nullable($ts->float()),
			'EPSEstimateNextQuarter' => $ts->nullable($ts->float()),
			'EPSEstimateCurrentQuarter' => $ts->nullable($ts->float()),
			'MostRecentQuarter' => $ts->nullable($ts->nonEmptyString()),
			'ProfitMargin' => $ts->nullable($ts->float()),
			'OperatingMarginTTM' => $ts->nullable($ts->float()),
			'ReturnOnAssetsTTM' => $ts->nullable($ts->float()),
			'ReturnOnEquityTTM' => $ts->nullable($ts->float()),
			'RevenueTTM' => $ts->before(IntegerAmount::roundToInt(...), $ts->nullable($ts->int())),
			'RevenuePerShareTTM' => $ts->nullable($ts->float()),
			'QuarterlyRevenueGrowthYOY' => $ts->nullable($ts->float()),
			'GrossProfitTTM' => $ts->before(IntegerAmount::roundToInt(...), $ts->nullable($ts->int())),
			'DilutedEpsTTM' => $ts->nullable($ts->float()),
			'QuarterlyEarningsGrowthYOY' => $ts->nullable($ts->float()),
		]);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($values instanceof Failure) {
			return $this->withOwnDefinition($values, $context);
		}

		$notices = null;
		if ($values instanceof WithNotices) {
			$notices = $values->notices;
			$values = $values->value;
		}

		// 3. Reindex values
		$reindexedValues = [];
		$reindexedValues['marketCapitalization'] = $values['MarketCapitalization'];
		$reindexedValues['marketCapitalizationMln'] = $values['MarketCapitalizationMln'];
		$reindexedValues['ebitda'] = $values['EBITDA'];
		$reindexedValues['peRatio'] = $values['PERatio'];
		$reindexedValues['pegRatio'] = $values['PEGRatio'];
		$reindexedValues['wallStreetTargetPrice'] = $values['WallStreetTargetPrice'];
		$reindexedValues['bookValue'] = $values['BookValue'];
		$reindexedValues['dividendShare'] = $values['DividendShare'];
		$reindexedValues['dividendYield'] = $values['DividendYield'];
		$reindexedValues['earningsShare'] = $values['EarningsShare'];
		$reindexedValues['epsEstimateCurrentYear'] = $values['EPSEstimateCurrentYear'];
		$reindexedValues['epsEstimateNextYear'] = $values['EPSEstimateNextYear'];
		$reindexedValues['epsEstimateNextQuarter'] = $values['EPSEstimateNextQuarter'];
		$reindexedValues['epsEstimateCurrentQuarter'] = $values['EPSEstimateCurrentQuarter'];
		$reindexedValues['mostRecentQuarter'] = $values['MostRecentQuarter'];
		$reindexedValues['profitMargin'] = $values['ProfitMargin'];
		$reindexedValues['operatingMarginTtm'] = $values['OperatingMarginTTM'];
		$reindexedValues['returnOnAssetsTtm'] = $values['ReturnOnAssetsTTM'];
		$reindexedValues['returnOnEquityTtm'] = $values['ReturnOnEquityTTM'];
		$reindexedValues['revenueTtm'] = $values['RevenueTTM'];
		$reindexedValues['revenuePerShareTtm'] = $values['RevenuePerShareTTM'];
		$reindexedValues['quarterlyRevenueGrowthYoy'] = $values['QuarterlyRevenueGrowthYOY'];
		$reindexedValues['grossProfitTtm'] = $values['GrossProfitTTM'];
		$reindexedValues['dilutedEpsTtm'] = $values['DilutedEpsTTM'];
		$reindexedValues['quarterlyEarningsGrowthYoy'] = $values['QuarterlyEarningsGrowthYOY'];

		unset($values['MarketCapitalization'], $values['MarketCapitalizationMln'], $values['EBITDA'], $values['PERatio'], $values['PEGRatio'], $values['WallStreetTargetPrice'], $values['BookValue'], $values['DividendShare'], $values['DividendYield'], $values['EarningsShare'], $values['EPSEstimateCurrentYear'], $values['EPSEstimateNextYear'], $values['EPSEstimateNextQuarter'], $values['EPSEstimateCurrentQuarter'], $values['MostRecentQuarter'], $values['ProfitMargin'], $values['OperatingMarginTTM'], $values['ReturnOnAssetsTTM'], $values['ReturnOnEquityTTM'], $values['RevenueTTM'], $values['RevenuePerShareTTM'], $values['QuarterlyRevenueGrowthYOY'], $values['GrossProfitTTM'], $values['DilutedEpsTTM'], $values['QuarterlyEarningsGrowthYOY']);
		$values = $reindexedValues + $values;

		// 4. Create a new instance
		$obj = new Highlights(...$values);

		return $notices === null ? $obj : new WithNotices($obj, $notices);
	}


	protected function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(Highlights::class);
	}
}
