<?php

declare(strict_types=1);

namespace Shredio\EodhdClient\Mapper;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\EodhdClient\Payload\Holder;
use Shredio\EodhdClient\TypeSchema\IntegerAmount;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Result\Failure;
use Shredio\TypeSchema\Result\WithNotices;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<Holder>
 */
final readonly class HolderMapper extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): Failure|WithNotices|Holder
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape(
			[
			'name' => $ts->string(),
			'date' => $ts->nullable($ts->nonEmptyString()),
			'totalShares' => $ts->nullable($ts->float()),
			'totalAssets' => $ts->nullable($ts->float()),
			'currentShares' => $ts->before(IntegerAmount::roundToInt(...), $ts->nullable($ts->int())),
			'change' => $ts->before(IntegerAmount::roundToInt(...), $ts->nullable($ts->int())),
			'change_p' => $ts->nullable($ts->float()),
		],
			identifier: 'name',
		);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($values instanceof Failure) {
			return $this->withOwnDefinition($values, $context);
		}

		$notices = null;
		if ($values instanceof WithNotices) {
			$notices = $values->notices;
			$values = $values->value;
		}

		// 3. Reindex values
		$reindexedValues = [];
		$reindexedValues['changePercent'] = $values['change_p'];

		unset($values['change_p']);
		$values = $reindexedValues + $values;

		// 4. Create a new instance
		$obj = new Holder(...$values);

		return $notices === null ? $obj : new WithNotices($obj, $notices);
	}


	protected function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(Holder::class);
	}
}
