<?php

declare(strict_types=1);

namespace Shredio\EodhdClient\Mapper;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\EodhdClient\Payload\IncomeStatement;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Result\Failure;
use Shredio\TypeSchema\Result\WithNotices;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<IncomeStatement>
 */
final readonly class IncomeStatementMapper extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): Failure|WithNotices|IncomeStatement
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape(
			[
			'date' => $ts->nonEmptyString(),
			'filing_date' => $ts->nullable($ts->nonEmptyString()),
			'currency_symbol' => $ts->nullable($ts->nonEmptyString()),
			'researchDevelopment' => $ts->nullable($ts->float()),
			'effectOfAccountingCharges' => $ts->nullable($ts->float()),
			'incomeBeforeTax' => $ts->nullable($ts->float()),
			'minorityInterest' => $ts->nullable($ts->float()),
			'netIncome' => $ts->nullable($ts->float()),
			'sellingGeneralAdministrative' => $ts->nullable($ts->float()),
			'sellingAndMarketingExpenses' => $ts->nullable($ts->float()),
			'grossProfit' => $ts->nullable($ts->float()),
			'reconciledDepreciation' => $ts->nullable($ts->float()),
			'ebit' => $ts->nullable($ts->float()),
			'ebitda' => $ts->nullable($ts->float()),
			'depreciationAndAmortization' => $ts->nullable($ts->float()),
			'nonOperatingIncomeNetOther' => $ts->nullable($ts->float()),
			'operatingIncome' => $ts->nullable($ts->float()),
			'otherOperatingExpenses' => $ts->nullable($ts->float()),
			'interestExpense' => $ts->nullable($ts->float()),
			'taxProvision' => $ts->nullable($ts->float()),
			'interestIncome' => $ts->nullable($ts->float()),
			'netInterestIncome' => $ts->nullable($ts->float()),
			'extraordinaryItems' => $ts->nullable($ts->float()),
			'nonRecurring' => $ts->nullable($ts->float()),
			'otherItems' => $ts->nullable($ts->float()),
			'incomeTaxExpense' => $ts->nullable($ts->float()),
			'totalRevenue' => $ts->nullable($ts->float()),
			'totalOperatingExpenses' => $ts->nullable($ts->float()),
			'costOfRevenue' => $ts->nullable($ts->float()),
			'totalOtherIncomeExpenseNet' => $ts->nullable($ts->float()),
			'discontinuedOperations' => $ts->nullable($ts->float()),
			'netIncomeFromContinuingOps' => $ts->nullable($ts->float()),
			'netIncomeApplicableToCommonShares' => $ts->nullable($ts->float()),
			'preferredStockAndOtherAdjustments' => $ts->nullable($ts->float()),
		],
			identifier: 'date',
		);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($values instanceof Failure) {
			return $this->withOwnDefinition($values, $context);
		}

		$notices = null;
		if ($values instanceof WithNotices) {
			$notices = $values->notices;
			$values = $values->value;
		}

		// 3. Reindex values
		$reindexedValues = [];
		$reindexedValues['filingDate'] = $values['filing_date'];
		$reindexedValues['currencySymbol'] = $values['currency_symbol'];

		unset($values['filing_date'], $values['currency_symbol']);
		$values = $reindexedValues + $values;

		// 4. Create a new instance
		$obj = new IncomeStatement(...$values);

		return $notices === null ? $obj : new WithNotices($obj, $notices);
	}


	protected function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(IncomeStatement::class);
	}
}
