<?php

declare(strict_types=1);

namespace Shredio\EodhdClient\Mapper;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\EodhdClient\Payload\InsiderTransaction;
use Shredio\EodhdClient\TypeSchema\IntegerAmount;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Result\Failure;
use Shredio\TypeSchema\Result\WithNotices;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<InsiderTransaction>
 */
final readonly class InsiderTransactionMapper extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): Failure|WithNotices|InsiderTransaction
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape(
			[
			'date' => $ts->nullable($ts->nonEmptyString()),
			'ownerCik' => $ts->nullable($ts->nonEmptyString()),
			'ownerName' => $ts->nullable($ts->nonEmptyString()),
			'transactionDate' => $ts->nullable($ts->nonEmptyString()),
			'transactionCode' => $ts->nullable($ts->nonEmptyString()),
			'transactionAmount' => $ts->before(IntegerAmount::roundToInt(...), $ts->nullable($ts->int())),
			'transactionPrice' => $ts->nullable($ts->float()),
			'transactionAcquiredDisposed' => $ts->nullable($ts->nonEmptyString()),
			'postTransactionAmount' => $ts->before(IntegerAmount::roundToInt(...), $ts->nullable($ts->int())),
			'secLink' => $ts->nullable($ts->nonEmptyString()),
		],
			identifier: 'ownerName',
		);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($values instanceof Failure) {
			return $this->withOwnDefinition($values, $context);
		}

		$notices = null;
		if ($values instanceof WithNotices) {
			$notices = $values->notices;
			$values = $values->value;
		}

		// 3. Create a new instance
		$obj = new InsiderTransaction(...$values);

		return $notices === null ? $obj : new WithNotices($obj, $notices);
	}


	protected function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(InsiderTransaction::class);
	}
}
