<?php

declare(strict_types=1);

namespace Shredio\EodhdClient\Mapper;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\EodhdClient\Payload\RealTimeQuote;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Result\Failure;
use Shredio\TypeSchema\Result\WithNotices;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<RealTimeQuote>
 */
final readonly class RealTimeQuoteMapper extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): Failure|WithNotices|RealTimeQuote
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape(
			[
			'code' => $ts->nonEmptyString(),
			'timestamp' => $ts->nullable($ts->int(), ['NA']),
			'gmtoffset' => $ts->int(),
			'open' => $ts->nullable($ts->float(), ['NA']),
			'high' => $ts->nullable($ts->float(), ['NA']),
			'low' => $ts->nullable($ts->float(), ['NA']),
			'close' => $ts->nullable($ts->float(), ['NA']),
			'volume' => $ts->nullable($ts->int(), ['NA']),
			'previousClose' => $ts->nullable($ts->float(), ['NA']),
			'change' => $ts->nullable($ts->float(), ['NA']),
			'change_p' => $ts->nullable($ts->float(), ['NA']),
		],
			identifier: 'code',
		);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($values instanceof Failure) {
			return $this->withOwnDefinition($values, $context);
		}

		$notices = null;
		if ($values instanceof WithNotices) {
			$notices = $values->notices;
			$values = $values->value;
		}

		// 3. Reindex values
		$reindexedValues = [];
		$reindexedValues['gmtOffset'] = $values['gmtoffset'];
		$reindexedValues['changePercent'] = $values['change_p'];

		unset($values['gmtoffset'], $values['change_p']);
		$values = $reindexedValues + $values;

		// 4. Create a new instance
		$obj = new RealTimeQuote(...$values);

		return $notices === null ? $obj : new WithNotices($obj, $notices);
	}


	protected function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(RealTimeQuote::class);
	}
}
