<?php

declare(strict_types=1);

namespace Shredio\EodhdClient\Mapper;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\EodhdClient\Payload\SharesStats;
use Shredio\EodhdClient\TypeSchema\IntegerAmount;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Result\Failure;
use Shredio\TypeSchema\Result\WithNotices;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<SharesStats>
 */
final readonly class SharesStatsMapper extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): Failure|WithNotices|SharesStats
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape([
			'SharesOutstanding' => $ts->before(IntegerAmount::roundToInt(...), $ts->nullable($ts->int())),
			'SharesFloat' => $ts->before(IntegerAmount::roundToInt(...), $ts->nullable($ts->int())),
			'PercentInsiders' => $ts->nullable($ts->float()),
			'PercentInstitutions' => $ts->nullable($ts->float()),
			'SharesShort' => $ts->before(IntegerAmount::roundToInt(...), $ts->nullable($ts->int())),
			'SharesShortPriorMonth' => $ts->before(IntegerAmount::roundToInt(...), $ts->nullable($ts->int())),
			'ShortRatio' => $ts->nullable($ts->float()),
			'ShortPercentOutstanding' => $ts->nullable($ts->float()),
			'ShortPercentFloat' => $ts->nullable($ts->float()),
		]);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($values instanceof Failure) {
			return $this->withOwnDefinition($values, $context);
		}

		$notices = null;
		if ($values instanceof WithNotices) {
			$notices = $values->notices;
			$values = $values->value;
		}

		// 3. Reindex values
		$reindexedValues = [];
		$reindexedValues['sharesOutstanding'] = $values['SharesOutstanding'];
		$reindexedValues['sharesFloat'] = $values['SharesFloat'];
		$reindexedValues['percentInsiders'] = $values['PercentInsiders'];
		$reindexedValues['percentInstitutions'] = $values['PercentInstitutions'];
		$reindexedValues['sharesShort'] = $values['SharesShort'];
		$reindexedValues['sharesShortPriorMonth'] = $values['SharesShortPriorMonth'];
		$reindexedValues['shortRatio'] = $values['ShortRatio'];
		$reindexedValues['shortPercentOutstanding'] = $values['ShortPercentOutstanding'];
		$reindexedValues['shortPercentFloat'] = $values['ShortPercentFloat'];

		unset($values['SharesOutstanding'], $values['SharesFloat'], $values['PercentInsiders'], $values['PercentInstitutions'], $values['SharesShort'], $values['SharesShortPriorMonth'], $values['ShortRatio'], $values['ShortPercentOutstanding'], $values['ShortPercentFloat']);
		$values = $reindexedValues + $values;

		// 4. Create a new instance
		$obj = new SharesStats(...$values);

		return $notices === null ? $obj : new WithNotices($obj, $notices);
	}


	protected function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(SharesStats::class);
	}
}
