<?php

declare(strict_types=1);

namespace Shredio\EodhdClient\Mapper;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\EodhdClient\Payload\SplitsDividends;
use Shredio\EodhdClient\TypeSchema\KeyedList;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Result\Failure;
use Shredio\TypeSchema\Result\WithNotices;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<SplitsDividends>
 */
final readonly class SplitsDividendsMapper extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): Failure|WithNotices|SplitsDividends
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape([
			'ForwardAnnualDividendRate' => $ts->nullable($ts->float()),
			'ForwardAnnualDividendYield' => $ts->nullable($ts->float()),
			'PayoutRatio' => $ts->nullable($ts->float()),
			'DividendDate' => $ts->nullable($ts->nonEmptyString()),
			'ExDividendDate' => $ts->nullable($ts->nonEmptyString()),
			'LastSplitFactor' => $ts->nullable($ts->nonEmptyString()),
			'LastSplitDate' => $ts->nullable($ts->nonEmptyString()),
			'NumberDividendsByYear' => $ts->before(KeyedList::values(...), $ts->list(new DividendCountByYearMapper())),
		]);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($values instanceof Failure) {
			return $this->withOwnDefinition($values, $context);
		}

		$notices = null;
		if ($values instanceof WithNotices) {
			$notices = $values->notices;
			$values = $values->value;
		}

		// 3. Reindex values
		$reindexedValues = [];
		$reindexedValues['forwardAnnualDividendRate'] = $values['ForwardAnnualDividendRate'];
		$reindexedValues['forwardAnnualDividendYield'] = $values['ForwardAnnualDividendYield'];
		$reindexedValues['payoutRatio'] = $values['PayoutRatio'];
		$reindexedValues['dividendDate'] = $values['DividendDate'];
		$reindexedValues['exDividendDate'] = $values['ExDividendDate'];
		$reindexedValues['lastSplitFactor'] = $values['LastSplitFactor'];
		$reindexedValues['lastSplitDate'] = $values['LastSplitDate'];
		$reindexedValues['numberDividendsByYear'] = $values['NumberDividendsByYear'];

		unset($values['ForwardAnnualDividendRate'], $values['ForwardAnnualDividendYield'], $values['PayoutRatio'], $values['DividendDate'], $values['ExDividendDate'], $values['LastSplitFactor'], $values['LastSplitDate'], $values['NumberDividendsByYear']);
		$values = $reindexedValues + $values;

		// 4. Create a new instance
		$obj = new SplitsDividends(...$values);

		return $notices === null ? $obj : new WithNotices($obj, $notices);
	}


	protected function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(SplitsDividends::class);
	}
}
