<?php

declare(strict_types=1);

namespace Shredio\EodhdClient\Mapper;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\EodhdClient\Payload\Technicals;
use Shredio\EodhdClient\TypeSchema\IntegerAmount;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Result\Failure;
use Shredio\TypeSchema\Result\WithNotices;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<Technicals>
 */
final readonly class TechnicalsMapper extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): Failure|WithNotices|Technicals
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape([
			'Beta' => $ts->nullable($ts->float()),
			'52WeekHigh' => $ts->nullable($ts->float()),
			'52WeekLow' => $ts->nullable($ts->float()),
			'50DayMA' => $ts->nullable($ts->float()),
			'200DayMA' => $ts->nullable($ts->float()),
			'SharesShort' => $ts->before(IntegerAmount::roundToInt(...), $ts->nullable($ts->int())),
			'SharesShortPriorMonth' => $ts->before(IntegerAmount::roundToInt(...), $ts->nullable($ts->int())),
			'ShortRatio' => $ts->nullable($ts->float()),
			'ShortPercent' => $ts->nullable($ts->float()),
		]);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($values instanceof Failure) {
			return $this->withOwnDefinition($values, $context);
		}

		$notices = null;
		if ($values instanceof WithNotices) {
			$notices = $values->notices;
			$values = $values->value;
		}

		// 3. Reindex values
		$reindexedValues = [];
		$reindexedValues['beta'] = $values['Beta'];
		$reindexedValues['fiftyTwoWeekHigh'] = $values['52WeekHigh'];
		$reindexedValues['fiftyTwoWeekLow'] = $values['52WeekLow'];
		$reindexedValues['fiftyDayMovingAverage'] = $values['50DayMA'];
		$reindexedValues['twoHundredDayMovingAverage'] = $values['200DayMA'];
		$reindexedValues['sharesShort'] = $values['SharesShort'];
		$reindexedValues['sharesShortPriorMonth'] = $values['SharesShortPriorMonth'];
		$reindexedValues['shortRatio'] = $values['ShortRatio'];
		$reindexedValues['shortPercent'] = $values['ShortPercent'];

		unset($values['Beta'], $values['52WeekHigh'], $values['52WeekLow'], $values['50DayMA'], $values['200DayMA'], $values['SharesShort'], $values['SharesShortPriorMonth'], $values['ShortRatio'], $values['ShortPercent']);
		$values = $reindexedValues + $values;

		// 4. Create a new instance
		$obj = new Technicals(...$values);

		return $notices === null ? $obj : new WithNotices($obj, $notices);
	}


	protected function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(Technicals::class);
	}
}
