<?php

declare(strict_types=1);

namespace Shredio\EodhdClient\Mapper;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\EodhdClient\Payload\User;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Result\Failure;
use Shredio\TypeSchema\Result\WithNotices;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<User>
 */
final readonly class UserMapper extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): Failure|WithNotices|User
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape([
			'name' => $ts->nullable($ts->nonEmptyString()),
			'email' => $ts->nullable($ts->nonEmptyString()),
			'subscriptionType' => $ts->nullable($ts->nonEmptyString()),
			'paymentMethod' => $ts->nullable($ts->nonEmptyString()),
			'apiRequests' => $ts->int(),
			'apiRequestsDate' => $ts->nonEmptyString(),
			'dailyRateLimit' => $ts->int(),
			'extraLimit' => $ts->int(),
			'inviteToken' => $ts->nullable($ts->nonEmptyString()),
			'inviteTokenClicked' => $ts->int(),
			'subscriptionMode' => $ts->nullable($ts->nonEmptyString()),
			'canManageOrganizations' => $ts->bool(),
		]);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($values instanceof Failure) {
			return $this->withOwnDefinition($values, $context);
		}

		$notices = null;
		if ($values instanceof WithNotices) {
			$notices = $values->notices;
			$values = $values->value;
		}

		// 3. Create a new instance
		$obj = new User(...$values);

		return $notices === null ? $obj : new WithNotices($obj, $notices);
	}


	protected function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(User::class);
	}
}
