<?php

declare(strict_types=1);

namespace Shredio\EodhdClient\Mapper;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\EodhdClient\Payload\Valuation;
use Shredio\EodhdClient\TypeSchema\IntegerAmount;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Result\Failure;
use Shredio\TypeSchema\Result\WithNotices;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<Valuation>
 */
final readonly class ValuationMapper extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): Failure|WithNotices|Valuation
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape([
			'TrailingPE' => $ts->nullable($ts->float()),
			'ForwardPE' => $ts->nullable($ts->float()),
			'PriceSalesTTM' => $ts->nullable($ts->float()),
			'PriceBookMRQ' => $ts->nullable($ts->float()),
			'EnterpriseValue' => $ts->before(IntegerAmount::roundToInt(...), $ts->nullable($ts->int())),
			'EnterpriseValueRevenue' => $ts->nullable($ts->float()),
			'EnterpriseValueEbitda' => $ts->nullable($ts->float()),
		]);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($values instanceof Failure) {
			return $this->withOwnDefinition($values, $context);
		}

		$notices = null;
		if ($values instanceof WithNotices) {
			$notices = $values->notices;
			$values = $values->value;
		}

		// 3. Reindex values
		$reindexedValues = [];
		$reindexedValues['trailingPe'] = $values['TrailingPE'];
		$reindexedValues['forwardPe'] = $values['ForwardPE'];
		$reindexedValues['priceSalesTtm'] = $values['PriceSalesTTM'];
		$reindexedValues['priceBookMrq'] = $values['PriceBookMRQ'];
		$reindexedValues['enterpriseValue'] = $values['EnterpriseValue'];
		$reindexedValues['enterpriseValueRevenue'] = $values['EnterpriseValueRevenue'];
		$reindexedValues['enterpriseValueEbitda'] = $values['EnterpriseValueEbitda'];

		unset($values['TrailingPE'], $values['ForwardPE'], $values['PriceSalesTTM'], $values['PriceBookMRQ'], $values['EnterpriseValue'], $values['EnterpriseValueRevenue'], $values['EnterpriseValueEbitda']);
		$values = $reindexedValues + $values;

		// 4. Create a new instance
		$obj = new Valuation(...$values);

		return $notices === null ? $obj : new WithNotices($obj, $notices);
	}


	protected function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(Valuation::class);
	}
}
